###############################################################################
## These functions support matrix inversion, storing the result of matrix
## inversions to be returned in subsequent calls for the inverse to a given
## matrix.
###############################################################################
###############################################################################
## makeCacheMatrix creates an object containing a list of functions to set and
## get the input matrix and functions to calculate the inverse and to return
## the inverse matrix.
###############################################################################
makeCacheMatrix <- function(x = matrix()) {
# set the stored inverse to NULL
    i<-NULL
# resets the list object with a new matrix
    set<-function(y){
# assigns the new input matrix
        x<<-y
# overwrites previously stored inverse matrix -primed to recalculate new matrix
        i<<-NULL
    }
# returns the stored input matrix
    get<-function() x
# (re)sets the stored inverse matrix
    setInv<-function(inverse) i <<- inverse
# gets the stored inverse matrix
    getInv<-function() i
# returns the list of functions with labels
    list(set=set, get=get, setInv=setInv, getInv = getInv)	
}
## Write a short comment describing this function
###############################################################################
## cacheSolve takes an list generated by a call to makeCacheMatrix and returns
## the inverse of the matrix associated with the object: if the inverse has
## not been calculated it performs this calculation else it returns the stored
## value
###############################################################################
cacheSolve <- function(x, ...) {
## x is the list returned by a call to makeCacheMatrix
## get the stored inverse matrix
    inv<-x$getInv()
## if an matrix is stored, return this along with a helpful message
    if(!is.null(inv)){
        message("Inverse matrix returned from cache")
        return(inv);
    }
## function continues IF no inverse matrix stored
## get the base matrix associated with the 'makeCacheMatrix' object
    matr<-x$get()
## print a helpful message - useful if the calculation is time consuming
    message("Inverse matrix calculated afresh: may take some time")
## calculate the inverse matrix.
## NOTE: There is no error checking - so dies if (eg) the matrix is singular
    inv<-solve(matr)
## set the stored inverse matrix
    x$setInv(inv)
## return the inverse matrix
    inv
}	
